### ISSUE TITLE
FIFO dead lock of monitor

### ISSUE THREAD

**Issue by kjkam** [lowasis/apollo_record#2]
Hi.

I reviewed your source code, and found critical problem.
In monitor process, it use FIFO for splitting from encoded AV packet to stream and file.
If encoded AV packet(producer of FIFO) is lager than size of the FIFO, it is blocked until reading from the FIFO.
But it process all in main thread, so it can't read from the FIFO because main thread is already blocked.
This senario makes FIFO dead lock.

Thank you.

**Comment by lowasis** [comment]
Dear sir.

I'll check it.

Thank you

**Comment by lowasis** [comment]
Dear sir.

Thank you for your contributing.
I tested your source code and merged to master branch.
It is very nice.

Thank you
