### ISSUE TITLE
AV lipsync issue

### ISSUE THREAD

**Issue by cafrii** [lowasis/apollo_record#8]
I am interested in this project. So I took the source and tried to run it. However, one problem is found and reported.
After a long time(about over ten hours) encoding the video and audio, more and more synchronization will be lost.
please check it.

**Comment by lowasis** [comment]
Dear sir

I'll check it.

Thank you

**Comment by lowasis** [comment]
Dear sir

you mean that AV sync is correct in the beginning, but gradually does not sync?
Default video framerate is 29.97Hz and audio samplerate is 48000Hz in NTSC.
I'll more check this issue

Thank you

**Comment by cafrii** [comment]
I found solution of this issue.
It was caused by an imprecise audio sampling rate.
Sampling of the sound card can not make exactly 48000 times per second and there may be slight differences. (E.g. 48000.049 Hz per second)
I'll commit soon the source that fixing this problem.

**Comment by lowasis** [comment]
I merged your source.
I will test your modification continuously.
Thank you

**Comment by lowasis** [comment]
I think this issue is resolved by your method.
I'll close
Thank you!
